@startuml
left to right direction
skinparam packageStyle rectangle
skinparam shadowing false

skinparam usecase {
  BackgroundColor #E0E0E0
  BorderColor #808080
}
skinparam actor {
  BackgroundColor white
  BorderColor black
}
skinparam rectangle {
  BackgroundColor #F5F5F5
  BorderColor #808080
}

actor "Administrator / Analyst" as Admin
actor "SentinelAI System(Backend)" as Backend
actor "Client" as Client
actor "GROQ (API)" as GROQ

rectangle "SentinelAI System" {
  usecase "Sign In / Role Assignment" as UC1
  usecase "Authentication" as UC2
  usecase "Review Vulnerabilities" as UC3
  usecase "Interact with AI Chat" as UC4
  usecase "Manage Projects & Target Scope" as UC5
  usecase "Launch & Monitor Scans" as UC6
  usecase "Generate PDF Assessment Report" as UC7
}

' Actors on the Left
Admin --> UC1
Admin --> UC3
Admin --> UC5

Backend --> UC2 : Verify
Backend --> UC6
Backend --> UC7

' Actors on the Right
UC1 <-- Client
UC3 <-- Client
UC7 <-- Client

UC4 <-- GROQ

' Use Case Dependencies
UC1 ..> UC2 : <<include>>
UC3 <.. UC4 : <<extend>>
UC5 <.. UC6 : <<extend>>
UC5 <.. UC7 : <<extend>>

@enduml
